
  Map<String, String> Countries = {
    'Mandarin Chinese': 'zh',
    'Spanish': 'es',
    'English': 'en',
    'Hindi': 'hi',
    'Arabic': 'ar',
    'Bengali': 'bn',
    'Portuguese': 'pt',
    'Russian': 'ru',
    'Urdu': 'ur',
    'Indonesian': 'id',
    'French': 'fr',
    'German': 'de',
    'Japanese': 'ja',
    'Punjabi': 'pa',
    'Vietnamese': 'vi',
    'Korean': 'ko',
    'Turkish': 'tr',
    'Italian': 'it',
    'Thai': 'th',
    'Persian (Farsi)': 'fa',
    'Telugu': 'te',
    'Tamil': 'ta',
    'Marathi': 'mr',
    'Gujarati': 'gu',
    'Malayalam': 'ml',
    'Kannada': 'kn',
    'Hausa': 'ha',
    'Swahili': 'sw',
    'Dutch': 'nl',
    'Filipino (Tagalog)': 'tl',
    'Romanian': 'ro',
    'Czech': 'cs',
    'Greek': 'el',
    'Hungarian': 'hu',
    'Swedish': 'sv',
    'Finnish': 'fi',
    'Norwegian': 'no',
    'Danish': 'da',
    'Bulgarian': 'bg',
    'Serbian': 'sr',
    'Croatian': 'hr',
    'Slovak': 'sk',
    'Lithuanian': 'lt',
    'Latvian': 'lv',
    'Estonian': 'et',
    'Icelandic': 'is',
    'Basque': 'eu',
    'Catalan': 'ca',
  };

